namespace SqlParser

open FParsec

module Lexer =
    let ws = spaces
    let token p = p .>> ws

    let reservedWords =
        Set.ofList
            [ "ADD"
              "ALL"
              "ALLOCATE"
              "ALTER"
              "AND"
              "ANY"
              "ARE"
              "ARRAY"
              "AS"
              "ASENSITIVE"
              "ASYMMETRIC"
              "AT"
              "ATOMIC"
              "AUTHORIZATION"
              "BEGIN"
              "BETWEEN"
              "BIGINT"
              "BINARY"
              "BLOB"
              "BOOLEAN"
              "BOTH"
              "BY"
              "CALL"
              "CALLED"
              "CASCADED"
              "CASE"
              "CAST"
              "CHAR"
              "CHARACTER"
              "CHECK"
              "CLOB"
              "CLOSE"
              "COLLATE"
              "COLUMN"
              "COMMIT"
              "CONNECT"
              "CONSTRAINT"
              "CONTINUE"
              "CORRESPONDING"
              "CREATE"
              "CROSS"
              "CUBE"
              "CURRENT"
              "CURRENT_DATE"
              "CURRENT_DEFAULT_TRANSFORM_GROUP"
              "CURRENT_PATH"
              "CURRENT_ROLE"
              "CURRENT_TIME"
              "CURRENT_TIMESTAMP"
              "CURRENT_TRANSFORM_GROUP_FOR_TYPE"
              "CURRENT_USER"
              "CURSOR"
              "CYCLE"
              "DATE"
              "DAY"
              "DEALLOCATE"
              "DEC"
              "DECIMAL"
              "DECLARE"
              "DEFAULT"
              "DELETE"
              "DEREF"
              "DESCRIBE"
              "DETERMINISTIC"
              "DISCONNECT"
              "DISTINCT"
              "DOUBLE"
              "DROP"
              "DYNAMIC"
              "EACH"
              "ELEMENT"
              "ELSE"
              "END"
              "END-EXEC"
              "ESCAPE"
              "EXCEPT"
              "EXCLUDE"
              "EXEC"
              "EXECUTE"
              "EXISTS"
              "EXTERNAL"
              "EXTRACT"
              "FALSE"
              "FETCH"
              "FILTER"
              "FLOAT"
              "FOLLOWING"
              "FOR"
              "FOREIGN"
              "FREE"
              "FROM"
              "FULL"
              "FUNCTION"
              "GET"
              "GLOBAL"
              "GRANT"
              "GROUP"
              "GROUPING"
              "HAVING"
              "HOLD"
              "HOUR"
              "IDENTITY"
              "IMMEDIATE"
              "IN"
              "INDICATOR"
              "INNER"
              "INOUT"
              "INPUT"
              "INSENSITIVE"
              "INSERT"
              "INT"
              "INTEGER"
              "INTERSECT"
              "INTERVAL"
              "INTO"
              "IS"
              "ISOLATION"
              "JOIN"
              "LANGUAGE"
              "LARGE"
              "LATERAL"
              "LEADING"
              "LEFT"
              "LIKE"
              "LIMIT"
              "LOCAL"
              "LOCALTIME"
              "LOCALTIMESTAMP"
              "MATCH"
              "MEMBER"
              "MERGE"
              "METHOD"
              "MINUTE"
              "MODIFIES"
              "MODULE"
              "MONTH"
              "MULTISET"
              "NATIONAL"
              "NATURAL"
              "NCHAR"
              "NCLOB"
              "NEW"
              "NEXT"
              "NO"
              "NONE"
              "NOT"
              "NULL"
              "NULLIF"
              "NUMERIC"
              "OF"
              "OFFSET"
              "OLD"
              "ON"
              "ONLY"
              "OPEN"
              "OR"
              "ORDER"
              "OTHERS"
              "OUT"
              "OUTER"
              "OUTPUT"
              "OVER"
              "OVERLAPS"
              "PARAMETER"
              "PARTITION"
              "PRECEDING"
              "PRECISION"
              "PREPARE"
              "PRIMARY"
              "PROCEDURE"
              "RANGE"
              "READS"
              "REAL"
              "RECURSIVE"
              "REF"
              "REFERENCES"
              "REFERENCING"
              "REGR_AVGX"
              "REGR_AVGY"
              "REGR_COUNT"
              "REGR_INTERCEPT"
              "REGR_R2"
              "REGR_SLOPE"
              "REGR_SXX"
              "REGR_SXY"
              "REGR_SYY"
              "RELEASE"
              "RESULT"
              "RETURN"
              "RETURNS"
              "REVOKE"
              "RIGHT"
              "ROLLBACK"
              "ROLLUP"
              "ROW"
              "ROWS"
              "SAVEPOINT"
              "SCROLL"
              "SEARCH"
              "SECOND"
              "SELECT"
              "SENSITIVE"
              "SESSION_USER"
              "SET"
              "SHARE"
              "SIMILAR"
              "SMALLINT"
              "SOME"
              "SPECIFIC"
              "SPECIFICTYPE"
              "SQL"
              "SQLEXCEPTION"
              "SQLSTATE"
              "SQLWARNING"
              "START"
              "STATIC"
              "SUBMULTISET"
              "SYMMETRIC"
              "SYSTEM"
              "SYSTEM_USER"
              "TABLE"
              "THEN"
              "TIES"
              "TIME"
              "TIMESTAMP"
              "TIMEZONE_HOUR"
              "TIMEZONE_MINUTE"
              "TO"
              "TRAILING"
              "TRANSLATION"
              "TREAT"
              "TRIGGER"
              "TRUE"
              "UESCAPE"
              "UNBOUNDED"
              "UNION"
              "UNIQUE"
              "UNKNOWN"
              "UNNEST"
              "UPDATE"
              "UPPER"
              "USER"
              "USING"
              "VALUE"
              "VALUES"
              "VAR_POP"
              "VAR_SAMP"
              "VARCHAR"
              "VARYING"
              "WHEN"
              "WHENEVER"
              "WHERE"
              "WIDTH_BUCKET"
              "WINDOW"
              "WITH"
              "WITHIN"
              "WITHOUT"
              "YEAR" ]

    let nonReservedWords =
        Set.ofList
            [ "A"
              "ABS"
              "ABSOLUTE"
              "ACTION"
              "ADA"
              "ADMIN"
              "AFTER"
              "ALWAYS"
              "ASC"
              "ASSERTION"
              "ASSIGNMENT"
              "ATTRIBUTE"
              "ATTRIBUTES"
              "AVG"
              "BEFORE"
              "BERNOULLI"
              "BREADTH"
              "C"
              "CARDINALITY"
              "CASCADE"
              "CATALOG"
              "CATALOG_NAME"
              "CEIL"
              "CEILING"
              "CHAIN"
              "CHARACTERISTICS"
              "CHARACTERS"
              "CHARACTER_LENGTH"
              "CHARACTER_SET_CATALOG"
              "CHARACTER_SET_NAME"
              "CHARACTER_SET_SCHEMA"
              "CHAR_LENGTH"
              "CHECKED"
              "CLASS_ORIGIN"
              "COALESCE"
              "COBOL"
              "CODE_UNITS"
              "COLLATION"
              "COLLATION_CATALOG"
              "COLLATION_NAME"
              "COLLATION_SCHEMA"
              "COLLECT"
              "COLUMN_NAME"
              "COMMAND_FUNCTION"
              "COMMAND_FUNCTION_CODE"
              "COMMITTED"
              "CONDITION"
              "CONDITION_NUMBER"
              "CONNECTION_NAME"
              "CONSTRAINTS"
              "CONSTRAINT_CATALOG"
              "CONSTRAINT_NAME"
              "CONSTRAINT_SCHEMA"
              "CONSTRUCTORS"
              "CONTAINS"
              "CONVERT"
              "CORR"
              "COUNT"
              "COVAR_POP"
              "COVAR_SAMP"
              "CUME_DIST"
              "CURRENT_COLLATION"
              "CURSOR_NAME"
              "DATA"
              "DATETIME_INTERVAL_CODE"
              "DATETIME_INTERVAL_PRECISION"
              "DEFAULTS"
              "DEFERRABLE"
              "DEFERRED"
              "DEFINED"
              "DEFINER"
              "DEGREE"
              "DENSE_RANK"
              "DEPTH"
              "DERIVED"
              "DESC"
              "DESCRIPTOR"
              "DIAGNOSTICS"
              "DISPATCH"
              "DOMAIN"
              "DYNAMIC_FUNCTION"
              "DYNAMIC_FUNCTION_CODE"
              "EQUALS"
              "EVERY"
              "EXCEPTION"
              "EXCLUDE"
              "EXCLUDING"
              "EXP"
              "EXTRACT"
              "FINAL"
              "FIRST"
              "FLOOR"
              "FOLLOWING"
              "FORTRAN"
              "FOUND"
              "FUSION"
              "G"
              "GENERAL"
              "GO"
              "GOTO"
              "GRANTED"
              "HIERARCHY"
              "IMPLEMENTATION"
              "INCLUDING"
              "INCREMENT"
              "INITIALLY"
              "INSTANCE"
              "INSTANTIABLE"
              "INTERSECTION"
              "INVOKER"
              "ISOLATION"
              "K"
              "KEY"
              "KEY_MEMBER"
              "KEY_TYPE"
              "LAST"
              "LENGTH"
              "LEVEL"
              "LN"
              "LOCATOR"
              "LOWER"
              "M"
              "MAP"
              "MATCHED"
              "MAX"
              "MAXVALUE"
              "MESSAGE_LENGTH"
              "MESSAGE_OCTET_LENGTH"
              "MESSAGE_TEXT"
              "MIN"
              "MINVALUE"
              "MOD"
              "MORE"
              "MUMPS"
              "NAME"
              "NAMES"
              "NESTING"
              "NEXT"
              "NORMALIZE"
              "NORMALIZED"
              "NULLABLE"
              "NULLIF"
              "NULLS"
              "NUMBER"
              "OBJECT"
              "OCTETS"
              "OCTET_LENGTH"
              "OPTION"
              "OPTIONS"
              "ORDERING"
              "ORDINALITY"
              "OTHERS"
              "OVERLAY"
              "OVERRIDING"
              "PAD"
              "PARAMETER_MODE"
              "PARAMETER_NAME"
              "PARAMETER_ORDINAL_POSITION"
              "PARAMETER_SPECIFIC_CATALOG"
              "PARAMETER_SPECIFIC_NAME"
              "PARAMETER_SPECIFIC_SCHEMA"
              "PARTIAL"
              "PASCAL"
              "PATH"
              "PERCENTILE_CONT"
              "PERCENTILE_DISC"
              "PERCENT_RANK"
              "PLACING"
              "PLI"
              "POSITION"
              "POWER"
              "PRECEDING"
              "PRESERVE"
              "PRIOR"
              "PRIVILEGES"
              "PUBLIC"
              "RANK"
              "READ"
              "RELATIVE"
              "REPEATABLE"
              "RESTART"
              "RETURNED_CARDINALITY"
              "RETURNED_LENGTH"
              "RETURNED_OCTET_LENGTH"
              "RETURNED_SQLSTATE"
              "ROLE"
              "ROUTINE"
              "ROUTINE_CATALOG"
              "ROUTINE_NAME"
              "ROUTINE_SCHEMA"
              "ROW_COUNT"
              "ROW_NUMBER"
              "SCALE"
              "SCHEMA"
              "SCHEMA_NAME"
              "SCOPE_CATALOG"
              "SCOPE_NAME"
              "SCOPE_SCHEMA"
              "SECTION"
              "SECURITY"
              "SELF"
              "SEQUENCE"
              "SERIALIZABLE"
              "SERVER_NAME"
              "SESSION"
              "SETS"
              "SIMPLE"
              "SIZE"
              "SOURCE"
              "SPACE"
              "SPECIFIC_NAME"
              "SQRT"
              "STATE"
              "STATEMENT"
              "STDDEV_POP"
              "STDDEV_SAMP"
              "STRUCTURE"
              "STYLE"
              "SUBCLASS_ORIGIN"
              "SUBSTRING"
              "SUM"
              "TABLESAMPLE"
              "TABLE_NAME"
              "TEMPORARY"
              "TIES"
              "TOP_LEVEL_COUNT"
              "TRANSACTION"
              "TRANSACTIONS_COMMITTED"
              "TRANSACTIONS_ROLLED_BACK"
              "TRANSACTION_ACTIVE"
              "TRANSFORM"
              "TRANSFORMS"
              "TRANSLATE"
              "TRIGGER_CATALOG"
              "TRIGGER_NAME"
              "TRIGGER_SCHEMA"
              "TRIM"
              "TYPE"
              "UNBOUNDED"
              "UNCOMMITTED"
              "UNDER"
              "UNNAMED"
              "USAGE"
              "USER_DEFINED_TYPE_CATALOG"
              "USER_DEFINED_TYPE_CODE"
              "USER_DEFINED_TYPE_NAME"
              "USER_DEFINED_TYPE_SCHEMA"
              "VIEW"
              "WORK"
              "WRITE"
              "ZONE" ]

    let pReservedWord: Parser<string, unit> =
        let isIdentifierChar c = isLetter c || isDigit c || c = '_'
        let p = many1Satisfy2L isLetter isIdentifierChar "reserved word"

        p
        >>= fun s ->
            let upper = s.ToUpperInvariant()

            if reservedWords.Contains upper then
                preturn upper
            else
                fail "not a reserved word"

    let pKeyword s : Parser<string, unit> =
        attempt (pstringCI s .>> notFollowedBy (asciiLetter <|> digit <|> pchar '_'))
        .>> ws

    let pIdentifier: Parser<string, unit> =
        let isIdentifierFirstChar c = isLetter c || c = '_'
        let isIdentifierChar c = isLetter c || isDigit c || c = '_'

        let pRegularIdentifier =
            attempt (
                many1Satisfy2L isIdentifierFirstChar isIdentifierChar "identifier"
                >>= fun s ->
                    let upper = s.ToUpperInvariant()

                    if reservedWords.Contains upper then
                        fail "reserved word"
                    else
                        preturn upper
            )

        let pDelimitedIdentifier =
            between (pchar '\"') (pchar '\"') (manyChars (attempt (pstring "\"\"") >>% '\"' <|> noneOf "\""))

        pRegularIdentifier <|> pDelimitedIdentifier .>> ws

    let pQuote = pchar '\''
    let pCharacterRepresentation = attempt (pstring "''") >>% '\'' <|> noneOf "'"

    let pCharacterStringLiteral: Parser<string, unit> =
        between pQuote pQuote (manyChars pCharacterRepresentation)
        .>>. many (attempt (ws >>. between pQuote pQuote (manyChars pCharacterRepresentation)))
        |>> fun (first, rest) -> String.concat "" (first :: rest)
        .>> ws

    let pNationalCharacterStringLiteral: Parser<string, unit> =
        pchar 'N' >>. pCharacterStringLiteral

    let pHexStringLiteral: Parser<byte[], unit> =
        pchar 'X'
        >>. between
                pQuote
                pQuote
                (many (
                    hex <|> digit .>>. (hex <|> digit)
                    |>> fun (h1, h2) -> System.Convert.ToByte(sprintf "%c%c" h1 h2, 16)
                ))
        |>> List.toArray
        .>> ws

    let pUnsignedInteger: Parser<uint64, unit> = many1Chars digit |>> uint64

    let pExactNumericLiteral: Parser<decimal, unit> =
        attempt (
            pipe2 (many1Chars digit) (opt (pchar '.' >>. manyChars digit)) (fun p f ->
                match f with
                | Some fStr -> decimal (p + "." + fStr)
                | None -> decimal p)
        )
        <|> (pchar '.' >>. many1Chars digit |>> fun f -> decimal ("0." + f))
        .>> ws

    let pApproximateNumericLiteral: Parser<decimal, unit> =
        attempt (
            pipe3
                pExactNumericLiteral
                (pchar 'E' <|> pchar 'e')
                (pipe2 (opt (pchar '+' <|> pchar '-')) (many1Chars digit) (fun s d ->
                    (Option.defaultValue '+' s |> string) + d))
                (fun m _ e -> m * decimal (10.0 ** float e))
        )
        .>> ws

    let pNumericLiteral: Parser<decimal, unit> =
        attempt pApproximateNumericLiteral <|> pExactNumericLiteral

    let pDateString = between pQuote pQuote (many1Chars (noneOf "'"))
    let pTimeString = between pQuote pQuote (many1Chars (noneOf "'"))
    let pTimestampString = between pQuote pQuote (many1Chars (noneOf "'"))

    let pDateLiteral: Parser<string, unit> = pKeyword "DATE" >>. pDateString .>> ws
    let pTimeLiteral: Parser<string, unit> = pKeyword "TIME" >>. pTimeString .>> ws

    let pTimestampLiteral: Parser<string, unit> =
        pKeyword "TIMESTAMP" >>. pTimestampString .>> ws

    let pBooleanLiteral: Parser<bool, unit> =
        pKeyword "TRUE" >>% true
        <|> (pKeyword "FALSE" >>% false)
        <|> (pKeyword "UNKNOWN" >>% false)
